import React from "react";
import "./index.css";

function Footer() {
	return (
		<div className="footer">
			<div className="footer__top"></div>
			<div className="footer__bottom">
				<div>
					Font generated by{" "}
					<a href="https://www.flaticon.com">flaticon.com</a>.
					<div>
						Under License:{" "}
						<a href="https://file000.flaticon.com/downloads/license/license.pdf">
							Flaticon Basic License
						</a>
						.
					</div>
					<div>
						By: <a href="http://www.freepik.com">Freepik</a>.
					</div>
				</div>
				<p>Copyright</p>
			</div>
		</div>
	);
}

export default Footer;
